name: Release

permissions:
  contents: write

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@9
        uses: pnpm/action-setup@v4
        with:
          version: '9.4.0'

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build frontend from source
        run: |
          pnpm i
          pnpm run build

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd)
          unzip "out/PowerControl.zip" -d "out/PowerControl"

      - name: Package plugin as TAR GZ
        run: |
          tar -czvf PowerControl.tar.gz --transform 's|out/PowerControl/PowerControl|PowerControl|' out/PowerControl/PowerControl/*

      - name: show files
        run: |
          tar -tzvf PowerControl.tar.gz
          7z l out/PowerControl.zip

      - name: Publish Installable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerControl-Installable
          path: out/PowerControl/*

      - name: Publish Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerControl-Release
          path: |
            PowerControl.tar.gz
            out/PowerControl.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/PowerControl-Release/PowerControl.tar.gz
            /tmp/artifacts/PowerControl-Release/out/PowerControl.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
